# Generated by Django 5.0 on 2024-03-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('plate_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('capacity', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
